# Generated by Django 4.0.2 on 2022-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_customer_company_alter_customer_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="street_number",
            field=models.CharField(max_length=10),
        ),
    ]
