# Generated by Django 4.0.2 on 2022-03-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeteoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("weather", models.IntegerField()),
                ("tmin", models.IntegerField()),
                ("tmax", models.IntegerField()),
                ("probarain", models.IntegerField()),
                ("probafrost", models.IntegerField()),
                ("probawind", models.IntegerField()),
                ("insee", models.CharField(max_length=10)),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Meteo",
            },
        ),
    ]
